# Generated by Django 5.2 on 2025-05-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_carrito_cliente_compra_detallecompra_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='INICIO_CATEGORIA',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='INICIO_COMUNA',
        ),
        migrations.AlterModelTable(
            name='detalle',
            table='INICIO_DETALLE',
        ),
        migrations.AlterModelTable(
            name='direccion',
            table='DIRECCION',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='INICIO_MARCA',
        ),
        migrations.AlterModelTable(
            name='modelo',
            table='INICIO_MODELO',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='INICIO_PRODUCTO',
        ),
        migrations.AlterModelTable(
            name='region',
            table='INICIO_REGION',
        ),
        migrations.AlterModelTable(
            name='tipoprod',
            table='INICIO_TIPOPROD',
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='INICIO_TIPOUSUARIO',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='INICIO_USUARIO',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='INICIO_VENTA',
        ),
    ]
