# Generated by Django 5.2 on 2025-05-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_carrito_compra_detallecompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalle',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoprod',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': False},
        ),
    ]
